---
title: "ds4da Agenda"
date: "Updated `r Sys.Date()`"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


## DA 3440: Data Science for Defense Analysis

<!-- ```{r, results='asis'} -->
<!-- library(kableExtra) -->

<!-- ds4da_book_root <- "https://knapply.github.io/ds4da-book/" -->

<!-- ds4da_schedule <- tibble::tribble( -->
<!--   ~Week,     ~Topic,                     ~Day,             ~`ds4da Chapter`, -->
<!--   1,         "Setting Up",               1,                "setup-r-and-rstudio", -->
<!--   1,         "Setting Up",               1,                "setup-coding-basics", -->
<!--   1,         "Setting Up",               1,                "setup-projects", -->
<!--   1,         "Setting Up",               2,                "setup-version-control", -->
<!--   1,         "Setting Up",               2,                "setup-rmarkdown", -->
<!--   2,         "Data Analysis I",          1,                "da1-importing-data", -->
<!--   2,         "Data Analysis I",          1,                "da1-data-frames", -->
<!--   2,         "Data Analysis I",          2,                "da1-tidy-data", -->
<!--   2,         "Data Analysis I",          2,                "da1-exporting-data" -->
<!--   # 3,     "Data Analysis II", -->
<!--   # 4,     "Data Analysis III", -->
<!--   # 5,     "R as a Programming Language", -->
<!--   # 6,     "Visualization - Going Deeper", -->
<!--   # 7,     "Spatial Data", -->
<!--   # 8,     "Graph Structures and Networks", -->
<!--   # 9,     "Data in the Wild", -->
<!--   # 10,     "Finishing Up" -->
<!-- ) -->

<!-- clean_chapter <- function(x) { -->
<!--   no_prefix <- stringr::str_remove(x, "^\\w+(?=-)") -->
<!--   no_hyphens <- stringr::str_replace_all(no_prefix, "-", " ") -->

<!--   stringr::str_to_title(no_hyphens) -->
<!-- } -->

<!-- ds4da_schedule$`ds4da Chapter` <- glue::glue( -->
<!--   '<a href="{ds4da_book_root}{ds4da_schedule$`ds4da Chapter`}.html">{clean_chapter(ds4da_schedule$`ds4da Chapter`)}</a>' -->
<!-- ) -->

<!-- ds4da_schedule %>%  -->
<!--   kable(escape = FALSE, row.names = FALSE) %>%  -->
<!--   kable_styling(full_width = TRUE) %>% -->
<!--   collapse_rows(columns = 1:3)  -->
<!-- ``` -->



```{r, results='asis'}
library(purrr)

ds4da_book_root <- "https://knapply.github.io/ds4da-book/"

ds4da_schedule <- tibble::tibble(
  Week = 1:9,
  Topic = c("Setting Up", "Data Analysis I", "Data Analysis II", "Data Analysis III",
            "R as a Programming Language", "Visualization", "Spatial Data",
            "Graphs and Networks", "Data in the Wild")
  ,
  Emphasis = c(
    NA, NA, NA,
    "Armed Groups",
    NA,
    "Proliferation",
    "Missile Capabilities",
    "Information Operations",
    "DPRK"
  )
  ,
  `Book Section` = list(
    c("setup-r-and-rstudio",
      "setup-coding-basics",
      "setup-projects",
      "setup-version-control",
      "setup-rmarkdown")
    ,
    c("da1-importing-data",
      "da1-data-frames",
      "da1-tidy-data",
      "da1-exporting-data")
    ,
    c("da2-text",
      "da2-dates-and-times")
    ,
    c("da3-relational-data")
    ,
    c("programming-objects",
      "programming-control-structures",
      "programming-functions",
      "programming-iteration"),
    NULL,
    NULL,
    NULL,
    NULL
  )
)


ds4da_schedule$`Book Section` <-  map_chr(ds4da_schedule$`Book Section`, ~ {
  # if (allnchar(.x) == 0) return("")
  # .x <- .x[nchar(.x) != 0]
  # if (length(.x) == 0) return("")
  if (is.null(.x)) return(NA_character_)

  no_prefix <- stringr::str_remove(.x, "^\\w+(?=-)")
  no_hyphens <- stringr::str_replace_all(no_prefix, "-", " ")
  title_case <- stringr::str_to_title(no_hyphens)

  res <- glue::glue(
    '-<a href="{ds4da_book_root}{.x}.html" target="_blank">{title_case}</a>'
  )

  stringr::str_flatten(res, "<br>")
})


ds4da_schedule %>%
  DT::datatable(
    escape = FALSE, rownames = FALSE,
    filter = "top",
    options = list(
      # autoWidth = TRUE,
      columnDefs = list(list(width = '10px', targets = 0)),
      dom = "ft", searchHighlight = TRUE, pageLength = nrow(ds4da_schedule)
    )
  ) %>%
  widgetframe::frameWidget(height = "auto")
```


<!-- ## Data Science for Practitioners -->

<!-- ```{r} -->
<!-- ds4p_schedule <- tibble::tribble( -->
<!--   ~Day,  ~Topic, -->
<!--   1,     "Setting Up, Data Analysis I", -->
<!--   2,     "Data Analysis II", -->
<!--   3,     "Data Analysis III", -->
<!--   4,     "Visualization - Going Deeper", -->
<!--   5,     "Putting it all Together" -->
<!-- ) -->

<!-- knitr::kable(ds4p_schedule) -->
<!-- ``` -->

